#!/bin/bash
 
iniciar(){
iptables -F -t nat
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
#iptables -t nat -A PREROUTING -p tcp -i eth1 --dport 80 -j REDIRECT --to 3128
}
 
parar(){
iptables -F -t nat
}

listar(){
iptables -L -t nat
}

case "$1" in
"start") iniciar ;;
"stop") parar ;;
"restart") parar; iniciar ;;
"status") listar ;;
*) echo "Use os parâmetros start ou stop"
esac
